language: node_js
sudo: false
node_js:
- '0.12'
- 4
- stable
script:
- npm test
- npm run doc
after_success:
- jsdoc/publish.sh
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_d4f181ef7c79_key -iv $encrypted_d4f181ef7c79_iv -in auth.js.enc -out test/resources/auth.js -d || true'
env:
  global:
    secure: I50FnfubwiZlol5Qs9tXPVACGbs+SG2dJLjpbzeio0Hl666d/hDuvf7IFwqqaRjQkmK2TdIjaGLMOgHxh/GGAoYf7LfZqjDID/tAhgoFOYiZwiPj66Z82F9P9cega2nkNW+125NzPuU3rhSCByG8+K/PMH/5JxPwPMoAYNLQjWc=
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: HI/hPaTNka02CzowbPse9weGF96Cx443yFxVZeS8g0S1GkByt9AEWv4W/aTxd6j2w67zRyNwk6foqnzoweUXNMso+DLM4v5HXshtagFEUiS++Ux3PfZttNTUP2VDSN8e7fjk8ZC/DHGxfuWhbHz9/BSTw2J2gZkKJ+MVFvfCOG0=
  on:
    tags: true
    repo: watson-developer-cloud/node-sdk
